#服务端口号
server:
  port: 8005

#服务应用名称
spring:
  application:
    name: consul-consumer-order
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


